

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BusinessLogicLayer.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class EnetCareEntities : DbContext
{
    public EnetCareEntities()
        : base("name=EnetCareEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<EnetClient> EnetClients { get; set; }

    public virtual DbSet<EnetDistrict> EnetDistricts { get; set; }

    public virtual DbSet<EnetIntervention> EnetInterventions { get; set; }

    public virtual DbSet<EnetInterventionType> EnetInterventionTypes { get; set; }

    public virtual DbSet<EnetUser> EnetUsers { get; set; }

}

}

