//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BusinessLogicLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnetIntervention
    {
        public int InterventionId { get; set; }
        public Nullable<int> InterventionTypeId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> ProposedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string DateToPerform { get; set; }
        public string MostRecentVisitDate { get; set; }
        public Nullable<int> LabourHours { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<double> Life { get; set; }
        public State State { get; set; }
        public string Note { get; set; }
    
        public virtual EnetClient EnetClient { get; set; }
        public virtual EnetDistrict EnetDistrict { get; set; }
        /// <summary>
        /// Approved by
        /// </summary>
        public virtual EnetUser EnetUser { get; set; }
        public virtual EnetInterventionType EnetInterventionType { get; set; }
        /// <summary>
        /// Proposed by
        /// </summary>
        public virtual EnetUser EnetUser1 { get; set; }
    }
}
