
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BusinessLogicLayer.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EnetUser
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EnetUser()
    {

        this.EnetInterventions = new HashSet<EnetIntervention>();

        this.EnetInterventions1 = new HashSet<EnetIntervention>();

    }


    public int UserId { get; set; }

    public string LoginName { get; set; }

    public string Name { get; set; }

    public BusinessLogicLayer.UserType Role { get; set; }

    public Nullable<int> DistrictId { get; set; }

    public Nullable<decimal> MaxCost { get; set; }

    public Nullable<int> MaxHours { get; set; }



    public virtual EnetDistrict EnetDistrict { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EnetIntervention> EnetInterventions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EnetIntervention> EnetInterventions1 { get; set; }

}

}
