//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENETCare.IMS.WebApp.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENET_Intervention
    {
        public int InterventionId { get; set; }
        public Nullable<int> InterventionTypeId { get; set; }
        public Nullable<int> ProposedBy { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> LabourHours { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string DateToPerform { get; set; }
        public string State { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string Note { get; set; }
        public Nullable<double> Life { get; set; }
        public string MostRecentVisitDate { get; set; }
        public string District { get; set; }
    
        public virtual ENET_Client ENET_Client { get; set; }
        public virtual ENET_District ENET_District { get; set; }
        public virtual ENET_User ENET_User { get; set; }
        public virtual ENET_InterventionType ENET_InterventionType { get; set; }
        public virtual ENET_SiteEngineer ENET_SiteEngineer { get; set; }
        public virtual ENET_State ENET_State { get; set; }
    }
}
