//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENETCare.IMS.WebApp.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENET_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENET_User()
        {
            this.ENET_Intervention = new HashSet<ENET_Intervention>();
            this.ENET_Manager = new HashSet<ENET_Manager>();
            this.ENET_SiteEngineer = new HashSet<ENET_SiteEngineer>();
        }
    
        public int UserId { get; set; }
        public string LoginName { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENET_Intervention> ENET_Intervention { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENET_Manager> ENET_Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENET_SiteEngineer> ENET_SiteEngineer { get; set; }
    }
}
