//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENETCare.IMS.WebApp.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENET_Manager
    {
        public int ManagerId { get; set; }
        public int UserId { get; set; }
        public string District { get; set; }
        public decimal MaxCost { get; set; }
        public int MaxHours { get; set; }
    
        public virtual ENET_District ENET_District { get; set; }
        public virtual ENET_User ENET_User { get; set; }
    }
}
